import os
import sys
import json
from pathlib import Path

TEMPLATES = {
    "Node.js Project": [
        "node_modules/", "dist/", "build/", "npm-debug.log*", "yarn-debug.log*",
        "yarn-error.log*", ".env", ".env.local"
    ],
    "React Application": [
        "node_modules/", "dist/", "build/", "npm-debug.log*", "yarn-debug.log*",
        "yarn-error.log*", ".env", ".env.local"
    ],
    "Python Project": [
        "__pycache__/", "*.py[cod]", "*$py.class", ".venv/", "venv/", "ENV/",
        "env/", ".env", "*.log"
    ],
    "Java Project (Maven)": [
        "target/", "build/", "*.class", "*.jar", "*.war", "*.nar", "*.ear", ".env"
    ],
    "Java Project (Gradle)": [
        "build/", ".gradle/", "*.class", "*.jar", "*.war", "*.nar", "*.ear", ".env"
    ],
    "C#/.NET Project": [
        "bin/", "obj/", "*.user", "*.suo", "*.userosscache", "*.sln.docstates", ".env"
    ],
    "Rust Project": [
        "target/", "**/*.rs.bk", ".env"
    ],
    "C/C++ Project": [
        "*.o", "*.obj", "*.a", "*.lib", "*.so", "*.dylib", "*.dll", "*.exe",
        "*.out", "build/", "CMakeCache.txt", "CMakeFiles/", ".env"
    ],
    "SQL/Database Project": [
        "*.bak", "*.mdf", "*.ldf", "*.db", "*.sqlite", ".env"
    ],
    "Docker Project": [
        ".env"
    ],
    "Generic/Other": [
        ".env", ".env.*", "*.log"
    ]
}

def generate_gitignore(repo_path: str, project_type: str) -> dict:
    if not os.path.isdir(repo_path):
        return {"success": False, "error": f"Not a directory: {repo_path}"}
        
    p = Path(repo_path)
    gitignore_path = p / ".gitignore"
    
    rules = TEMPLATES.get(project_type, TEMPLATES["Generic/Other"])
    
    if gitignore_path.exists():
        try:
            with open(gitignore_path, "r", encoding="utf-8") as f:
                existing_lines = f.read().splitlines()
        except Exception as e:
            return {"success": False, "error": f"Failed to read existing .gitignore: {str(e)}"}
            
        existing_rules = set()
        for line in existing_lines:
            line_clean = line.strip()
            if line_clean and not line_clean.startswith("#"):
                existing_rules.add(line_clean)
                
        missing_rules = [r for r in rules if r not in existing_rules]
        
        if not missing_rules:
            return {
                "success": True,
                "message": "Existing .gitignore is already up to date.",
                "updated": False
            }
            
        try:
            with open(gitignore_path, "a", encoding="utf-8") as f:
                f.write("\n\n# --- Added by GitHub Automator ---\n")
                for mr in missing_rules:
                    f.write(f"{mr}\n")
            return {
                "success": True,
                "message": f"Appended {len(missing_rules)} missing rules to existing .gitignore.",
                "updated": True
            }
        except Exception as e:
            return {"success": False, "error": f"Failed to append to .gitignore: {str(e)}"}
            
    else:
        try:
            with open(gitignore_path, "w", encoding="utf-8") as f:
                f.write(f"# Gitignore for {project_type} project generated by GitHub Automator\n\n")
                for r in rules:
                    f.write(f"{r}\n")
            return {
                "success": True,
                "message": f"Created new .gitignore for {project_type} project.",
                "updated": True
            }
        except Exception as e:
            return {"success": False, "error": f"Failed to write .gitignore: {str(e)}"}

if __name__ == "__main__":
    args = json.loads(sys.stdin.read())
    repo_path = args.get("repo_path", "")
    project_type = args.get("project_type", "Generic/Other")
    result = generate_gitignore(repo_path, project_type)
    print(json.dumps(result))
